version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/elixir:1.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "mix.lock" }}
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test
      - run: mix credo --mute-exit-status
      - save_cache:
          key: dependency-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
